### Libraries

In [1]:
import pandas as pd

### From python files

### Loading data

In [67]:
all_df = pd.read_csv("../../data/raw/HR_data_2/HR_data_2.csv")

### Data overview

In [68]:
all_df = all_df.rename(columns={"Unnamed: 0": "ID"})#clarifying numeration of observations column name
all_df.head()

,ID,HR_TD_Mean,HR_TD_Median,HR_TD_std,HR_TD_Min,HR_TD_Max,HR_TD_AUC,HR_TD_Kurtosis,HR_TD_Skew,HR_TD_Slope_min,...,upset,hostile,alert,ashamed,inspired,nervous,attentive,afraid,active,determined
0,0,78.663878,76.70,7.480043,67.25,92.48,23048.450,-1.091448,0.369955,-0.7300,...,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,2.0
1,1,76.540732,76.61,2.584756,69.82,82.33,23959.920,-0.245338,0.338732,-0.3600,...,2.0,1.0,3.0,2.0,2.0,2.0,3.0,1.0,3.0,3.0
2,2,78.173563,77.92,2.681255,72.22,82.80,20324.605,-0.615922,-0.233047,-0.6300,...,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,3.0,3.0
3,3,83.073688,83.88,7.363598,69.42,96.12,24924.300,-0.866610,-0.046021,-0.4650,...,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,3.0,3.0
4,4,72.281250,72.91,3.193762,64.95,79.98,23052.100,0.200401,-0.560948,-0.3725,...,3.0,1.0,3.0,2.0,3.0,3.0,4.0,2.0,4.0,4.0

In [ ]:
#Checking for missing values
all_df.isna().any().any()

np.True_

In [ ]:
#Checking how many missing values there are
all_df.isna().sum().sum()

np.int64(9)

In [ ]:
#Checking which columns have missing values and how many
all_df.isna().sum()[all_df.isna().sum() > 0]

EDA_TD_P_RT     1
EDA_TD_P_ReT    1
inspired        2
attentive       1
afraid          1
active          1
determined      2
dtype: int64

In [85]:
#Checking which rows have missing values and which columns are affected in those rows
rows_with_na = all_df[all_df.isna().any(axis=1)]
rows_with_na_only_affected_cols = rows_with_na.loc[:, rows_with_na.isna().any(axis=0)]
rows_with_na_only_affected_cols

,EDA_TD_P_RT,EDA_TD_P_ReT,inspired,attentive,afraid,active,determined
104,2.321429,1.892857,2.0,NaN,NaN,NaN,NaN
120,1.968750,2.703125,2.0,2.0,1.0,2.0,NaN
122,3.387500,2.367647,NaN,3.0,1.0,2.0,3.0
125,2.108696,1.911765,NaN,3.0,4.0,2.0,2.0
272,NaN,NaN,2.0,3.0,1.0,3.0,3.0

### Splitting

Data is splitted into more manageable tables.

In [69]:
#all data from the sensors
sens_df = all_df.iloc[:,0:52]
sens_df.head()

,ID,HR_TD_Mean,HR_TD_Median,HR_TD_std,HR_TD_Min,HR_TD_Max,HR_TD_AUC,HR_TD_Kurtosis,HR_TD_Skew,HR_TD_Slope_min,...,EDA_TD_T_AUC,EDA_TD_T_Kurtosis,EDA_TD_T_Skew,EDA_TD_T_Slope_min,EDA_TD_T_Slope_max,EDA_TD_T_Slope_mean,EDA_TD_T_Slope,EDA_TD_P_Peaks,EDA_TD_P_RT,EDA_TD_P_ReT
0,0,78.663878,76.70,7.480043,67.25,92.48,23048.450,-1.091448,0.369955,-0.7300,...,213.374114,1.345997,-1.379434,-0.000144,0.000138,0.000010,1.036040e-05,11,2.522727,2.075000
1,1,76.540732,76.61,2.584756,69.82,82.33,23959.920,-0.245338,0.338732,-0.3600,...,213.235380,0.887010,0.854067,-0.000146,0.000165,0.000009,7.714503e-06,15,2.214286,2.192308
2,2,78.173563,77.92,2.681255,72.22,82.80,20324.605,-0.615922,-0.233047,-0.6300,...,173.465157,0.205817,0.480581,-0.000112,0.000132,0.000002,1.799914e-06,10,1.972222,2.111111
3,3,83.073688,83.88,7.363598,69.42,96.12,24924.300,-0.866610,-0.046021,-0.4650,...,191.943390,2.488339,1.246665,-0.000455,0.000481,-0.000001,-1.355151e-07,12,1.886364,1.805556
4,4,72.281250,72.91,3.193762,64.95,79.98,23052.100,0.200401,-0.560948,-0.3725,...,192.341180,1.196508,1.592099,-0.000420,0.000334,0.000014,1.267198e-05,20,1.812500,1.926471

In [70]:
#heart rate data
sens_hr_df = all_df.iloc[:, 0:13]
sens_hr_df.head()

,ID,HR_TD_Mean,HR_TD_Median,HR_TD_std,HR_TD_Min,HR_TD_Max,HR_TD_AUC,HR_TD_Kurtosis,HR_TD_Skew,HR_TD_Slope_min,HR_TD_Slope_max,HR_TD_Slope_mean,HR_TD_Slope
0,0,78.663878,76.70,7.480043,67.25,92.48,23048.450,-1.091448,0.369955,-0.7300,0.9775,0.044590,0.046701
1,1,76.540732,76.61,2.584756,69.82,82.33,23959.920,-0.245338,0.338732,-0.3600,0.1900,-0.028095,-0.024148
2,2,78.173563,77.92,2.681255,72.22,82.80,20324.605,-0.615922,-0.233047,-0.6300,0.3575,-0.024202,-0.026008
3,3,83.073688,83.88,7.363598,69.42,96.12,24924.300,-0.866610,-0.046021,-0.4650,0.6500,0.021375,0.021477
4,4,72.281250,72.91,3.193762,64.95,79.98,23052.100,0.200401,-0.560948,-0.3725,0.3375,-0.013555,-0.012871

In [71]:
#temperature data
sens_temp_df = all_df.iloc[:, [0,13,14,15,16,17,18,19,20,21,22,23,24]]
sens_temp_df.head()

,ID,TEMP_TD_Mean,TEMP_TD_Median,TEMP_TD_std,TEMP_TD_Min,TEMP_TD_Max,TEMP_TD_AUC,TEMP_TD_Kurtosis,TEMP_TD_Skew,TEMP_TD_Slope_min,TEMP_TD_Slope_max,TEMP_TD_Slope_mean,TEMP_TD_Slope
0,0,31.090000,31.11,0.163895,30.59,31.31,36593.14,1.349570,-1.352915,-0.002286,0.000377,-0.000589,-0.000455
1,1,30.937293,30.93,0.083766,30.81,31.17,38826.24,0.177872,0.898894,-0.001062,0.000714,0.000232,0.000241
2,2,30.735341,30.75,0.078038,30.59,30.89,31964.72,-0.956503,-0.143041,-0.000962,0.000777,-0.000085,-0.000155
3,3,30.505025,30.29,0.366089,30.11,31.15,36758.35,-1.513910,0.503921,-0.000556,0.002963,0.000667,0.000704
4,4,30.332578,30.35,0.110119,30.11,30.53,38795.38,-1.456255,-0.171929,-0.000962,0.000192,-0.000314,-0.000300

In [72]:
#eda phasic data 
sens_eda_p_df = all_df.iloc[:, [0,25,26,27,28,29,30,31,32,33,34,35,36,49,50,51]]
sens_eda_p_df.head()

,ID,EDA_TD_P_Mean,EDA_TD_P_Median,EDA_TD_P_std,EDA_TD_P_Min,EDA_TD_P_Max,EDA_TD_P_AUC,EDA_TD_P_Kurtosis,EDA_TD_P_Skew,EDA_TD_P_Slope_min,EDA_TD_P_Slope_max,EDA_TD_P_Slope_mean,EDA_TD_P_Slope,EDA_TD_P_Peaks,EDA_TD_P_RT,EDA_TD_P_ReT
0,0,0.000172,0.000006,0.000927,-0.006185,0.007375,0.202712,28.467716,1.091696,-0.000200,0.000198,-0.000004,4.360220e-06,11,2.522727,2.075000
1,1,0.000489,0.000035,0.001138,0.000000,0.008462,0.614382,18.455509,3.948751,-0.000273,0.000451,0.000001,-2.617585e-06,15,2.214286,2.192308
2,2,0.000155,0.000002,0.000444,0.000000,0.005550,0.161122,36.768442,5.151764,-0.000045,0.000054,-0.000001,-1.084815e-06,10,1.972222,2.111111
3,3,0.000673,0.000018,0.001829,0.000000,0.012784,0.811271,19.045235,4.165664,-0.000271,0.000309,0.000002,-5.062888e-08,12,1.886364,1.805556
4,4,0.001164,0.000074,0.002936,-0.001992,0.022954,1.484085,20.998111,4.209074,-0.000646,0.000639,0.000005,1.344367e-05,20,1.812500,1.926471

In [73]:
#eda tonic data
sens_eda_t_df = all_df.iloc[:, [0,37,38,39,40,41,42,43,44,45,46,47,48]]
sens_eda_t_df.head()

,ID,EDA_TD_T_Mean,EDA_TD_T_Median,EDA_TD_T_std,EDA_TD_T_Min,EDA_TD_T_Max,EDA_TD_T_AUC,EDA_TD_T_Kurtosis,EDA_TD_T_Skew,EDA_TD_T_Slope_min,EDA_TD_T_Slope_max,EDA_TD_T_Slope_mean,EDA_TD_T_Slope
0,0,0.181286,0.182695,0.003744,0.169440,0.186816,213.374114,1.345997,-1.379434,-0.000144,0.000138,0.000010,1.036040e-05
1,1,0.169909,0.169617,0.002976,0.164504,0.179273,213.235380,0.887010,0.854067,-0.000146,0.000165,0.000009,7.714503e-06
2,2,0.166798,0.166706,0.002266,0.162036,0.172624,173.465157,0.205817,0.480581,-0.000112,0.000132,0.000002,1.799914e-06
3,3,0.159292,0.158034,0.004789,0.148368,0.175496,191.943390,2.488339,1.246665,-0.000455,0.000481,-0.000001,-1.355151e-07
4,4,0.150387,0.147895,0.006473,0.143003,0.168106,192.341180,1.196508,1.592099,-0.000420,0.000334,0.000014,1.267198e-05

In [74]:
#metadata about observations
meta_df = all_df.iloc[:, [0,52,53,54,55,56,57,58,60]]
meta_df.head()

,ID,Round,Phase,Individual,Puzzler,original_ID,raw_data_path,Team_ID,Cohort
0,0,round_3,phase3,1,1,19.0,dataset/D1_4/ID_1/round_3/phase3,D1_4_Team10,D1_4
1,1,round_3,phase2,1,1,19.0,dataset/D1_4/ID_1/round_3/phase2,D1_4_Team10,D1_4
2,2,round_3,phase1,1,1,19.0,dataset/D1_4/ID_1/round_3/phase1,D1_4_Team10,D1_4
3,3,round_2,phase3,1,1,19.0,dataset/D1_4/ID_1/round_2/phase3,D1_4_Team10,D1_4
4,4,round_2,phase2,1,1,19.0,dataset/D1_4/ID_1/round_2/phase2,D1_4_Team10,D1_4

In [66]:
#I-PANAS-SF questionnaire answers data
panas_df = all_df.iloc[:, [0,61,62,63,64,65,66,67,68,69,70]]
panas_df.head()

,ID,upset,hostile,alert,ashamed,inspired,nervous,attentive,afraid,active,determined
0,0,1.0,1.0,2.0,1.0,2.0,2.0,3.0,1.0,2.0,2.0
1,1,2.0,1.0,3.0,2.0,2.0,2.0,3.0,1.0,3.0,3.0
2,2,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,3.0,3.0
3,3,1.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,3.0,3.0
4,4,3.0,1.0,3.0,2.0,3.0,3.0,4.0,2.0,4.0,4.0

In [65]:
#other querstions data
restQ_df = all_df.iloc[:, [0,59]]
restQ_df.head()

   ID  Frustrated
0   0         2.0
1   1         3.0
2   2         2.0
3   3         2.0
4   4         2.0

###